name: jshy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6351086844224483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.36000843555666506
  lightness: 0.46823398186825216
  saturation: 0.08911684481427073
  rhythmicContrast: 0.46186736575327814
purpose: []
